// Mocks generated by Mockito 5.2.0 from annotations
// in dalle_mobile_client/test/generation_details_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:dalle_mobile_client/models/dalle_image.dart' as _i4;
import 'package:dalle_mobile_client/repositories/interfaces/saved_screenshots_repository.dart'
    as _i2;
import 'package:dalle_mobile_client/services/interfaces/share_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SavedScreenshotsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedScreenshotsRepository extends _i1.Mock
    implements _i2.SavedScreenshotsRepository {
  MockSavedScreenshotsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DalleImage?> getScreenshotData() =>
      (super.noSuchMethod(Invocation.method(#getScreenshotData, []),
              returnValue: Future<_i4.DalleImage?>.value())
          as _i3.Future<_i4.DalleImage?>);
  @override
  _i3.Future<String?> saveScreenshotData(_i5.Uint8List? screenshotData) =>
      (super.noSuchMethod(
          Invocation.method(#saveScreenshotData, [screenshotData]),
          returnValue: Future<String?>.value()) as _i3.Future<String?>);
}

/// A class which mocks [ShareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShareService extends _i1.Mock implements _i6.ShareService {
  MockShareService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> shareFile(String? filePath,
          {String? subject, String? text}) =>
      (super.noSuchMethod(
          Invocation.method(
              #shareFile, [filePath], {#subject: subject, #text: text}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
