// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0U6pBpc3THrN_ur7Gb0QPMCvSf1rwr-c',
    appId: '1:56265481836:web:e1619bcb6d80817d440249',
    messagingSenderId: '56265481836',
    projectId: 'dalle-mini-client',
    authDomain: 'dalle-mini-client.firebaseapp.com',
    storageBucket: 'dalle-mini-client.appspot.com',
    measurementId: 'G-V5MQBZJR2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVyhLGIOD9W_XicDOzdN6Izjkup-tl9g',
    appId: '1:56265481836:android:b302c651dd3bab7f440249',
    messagingSenderId: '56265481836',
    projectId: 'dalle-mini-client',
    storageBucket: 'dalle-mini-client.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Po_iK0Y6HS0uYGBwhrip8d3IjDXr5VM',
    appId: '1:56265481836:ios:98062948f57996c7440249',
    messagingSenderId: '56265481836',
    projectId: 'dalle-mini-client',
    storageBucket: 'dalle-mini-client.appspot.com',
    iosClientId: '56265481836-bqrqbcf321n46r7tqdaia32vevo0len4.apps.googleusercontent.com',
    iosBundleId: 'com.example.dalleMobileClient',
  );
}
